name: Continuous integration

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:latest
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672/tcp
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v1
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-suggest
      # - name: Run PSALM checks
      #   run: composer run-script psalm
      # - name: Check code style
      #   run: composer run-script php-cs-fixer-check
      - name: getRabbitPort
        run: |
          ls ${{ job.services.rabbitmq.ports[5672] }}
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          MSAPP_RABBITMQ_PORT: ${{ job.services.rabbitmq.ports[5672] }}
        run: composer run-script testdox
      # - name: Upload coverage
      #   run: bash <(curl -s https://codecov.io/bash)
